spring:
  profiles:
    active: was1

---
spring:
  config:
    activate:
      on-profile: was1

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: was2

server:
  port: 8080