spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f508bf6ede31a21a675b681c026f47d8
            client-secret: qrULgwSfjHJQyap2giDufmRuzdomuVqQ
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  cache:
    type: redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}

client:
  host: ${CLIENT_HOST}
  url: ${CLIENT_URL}
  endpoint: ${CLIENT_ENDPOINT}

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: bloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingbloomingblooming

---
spring:
  config:
    activate:
      on-profile: test
